default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: \\*default
  adapter: postgresql
  database: RailsGame
  username: RailsGame
  password: RailsGame
  host: localhost

test:
  <<: \\*default
  adapter: postgresql
  database: RailsGame_test
  username: RailsGame
  password: RailsGame
  host: localhost

production:
  <<: \\*default
  adapter: postgresql
  database: RailsGame_production
  username: RailsGame
  password: RailsGame
  host: localhost